"""add_image_url_to_menu_categories

Revision ID: 72cd2f329ca7
Revises: 072485d371e4
Create Date: 2025-04-22 07:37:58.122105+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72cd2f329ca7'
down_revision: Union[str, None] = '072485d371e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_categories', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_categories', 'image_url')
    # ### end Alembic commands ###
