"""Menu Categories Table

Revision ID: 072485d371e4
Revises: 66c18e6638b4
Create Date: 2025-04-18 12:49:25.774699+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072485d371e4'
down_revision: Union[str, None] = '66c18e6638b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_categories_name'), 'menu_categories', ['name'], unique=False)
    op.add_column('menus', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'menus', 'menu_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menus', type_='foreignkey')
    op.drop_column('menus', 'category_id')
    op.drop_index(op.f('ix_menu_categories_name'), table_name='menu_categories')
    op.drop_table('menu_categories')
    # ### end Alembic commands ###
